Repository confidential-nt/memo-fe, pull requests merged in 2023-11, with the labels that each got.

#7 indexedDB로 사용자가 로그인 하지 않아도 메모장 CRUD 할 수 있는 기능 구현
  krampoline/package-lock.json
  krampoline/package.json
  krampoline/src/components/memo/TextEditor.tsx
  krampoline/src/components/memo/TreePannel.tsx
  krampoline/src/components/memo/TreeView.tsx
  krampoline/src/components/memo/TreeViewHOC.tsx
  krampoline/src/components/memo/node/Node.tsx
  krampoline/src/context/UserContext.tsx
  krampoline/src/hooks/useMemoActions.tsx
  krampoline/src/layout/Layout.tsx
  krampoline/src/pages/Memo.tsx
  krampoline/src/service/database/api.ts
  krampoline/src/service/database/db.ts
  krampoline/src/service/types/db.types.ts
  krampoline/src/types/Memo.types.ts
Labels: new feature

#8 캘린더 띄우기 & 입력 모달창 생성
  krampoline/package-lock.json
  krampoline/package.json
  krampoline/src/App.tsx
  krampoline/src/components/calendarDialog/CalendarDialog.tsx
  krampoline/src/components/calendarDialog/timePicker.css
  krampoline/src/pages/Calendar.tsx
  krampoline/src/pages/MyCalendar.tsx
Labels: new feature

#9 다른 크기의 화면 view에서 Memo 페이지의 UI 이상하게 보이는 것 수정
  krampoline/src/components/memo/TextEditor.tsx
  krampoline/src/components/memo/TreeView.tsx
  krampoline/src/pages/Memo.tsx
Labels: fix

#11 Todo입력 모달창 반응형 스타일로 수정
  krampoline/src/components/calendarDialog/CalendarDialog.tsx
Labels: new feature

#12 투두 리스트 수정 기능 구현, 코드 수정
  krampoline/package-lock.json
  krampoline/src/components/todo/Task.tsx
Labels: new feature

#13 날짜 선택했을 때 하루 더 더해지는 오류 수정
  krampoline/src/components/calendarDialog/CalendarDialog.tsx
Labels: fix

#14 사용자 경험 향상을 위한 트리뷰 토글할 수 있는 버튼 구현
  krampoline/src/layout/Layout.tsx
  krampoline/src/pages/Memo.tsx
Labels: new feature

#15 투두 리스트 반응형 여백 조정
  krampoline/package-lock.json
  krampoline/package.json
  krampoline/src/pages/Todo.tsx
Labels: design

#16 투두 리스트 반응형 화면 배치 변경
  krampoline/src/pages/Todo.tsx
Labels: design

#18 쓰지않는 css파일 제거
  krampoline/src/components/CalendarDialog.tsx
  krampoline/src/components/calendarDialog/timePicker.css
  krampoline/src/pages/Calendar.tsx
  krampoline/src/pages/MyCalendar.tsx
Labels: new feature

#20 날짜가 이틀로 설정되는 오류 & eventsData null 처리
  krampoline/src/components/calendar/CalendarDialog.tsx
  krampoline/src/pages/MyCalendar.tsx
Labels: fix

#21 투두 리스트 로컬에서 RUD 기능 및 필터 기능 구현
  krampoline/src/components/todo/Task.tsx
  krampoline/src/pages/Todo.tsx
Labels: new feature

#24 Dialog 디자인 길이 맞추기
  krampoline/src/components/CalendarDialog.tsx
  krampoline/src/components/calendar/CalendarDialog.tsx
  krampoline/src/components/calendar/EditDialog.tsx
  krampoline/src/components/todo/Tasks.tsx
  krampoline/src/pages/Calendar.tsx
Labels: fix

#25 카카오 로그인 연결
  krampoline/.eslintrc.cjs
  krampoline/package-lock.json
  krampoline/package.json
  krampoline/src/App.tsx
  krampoline/src/Router.tsx
  krampoline/src/common/kakao.ts
  krampoline/src/common/route.ts
  krampoline/src/components/Header.tsx
  krampoline/src/context/AuthContext.tsx
  krampoline/src/pages/Login.tsx
  krampoline/src/service/http-requests/kakao-api.ts
  krampoline/src/utils/token.ts
Labels: new feature

#26 프로덕션 환경에서 /today로 들어가면 제대로 페이지 못불러오는 에러 수정 시도 1
  krampoline/vercel.json
Labels: fix

#27 메모 네트워크 통신 및 동기화 구현
  krampoline/package-lock.json
  krampoline/package.json
  krampoline/src/App.tsx
  krampoline/src/common/local-storage.ts
  krampoline/src/common/route.ts
  krampoline/src/components/Header.tsx
  krampoline/src/components/Navbar.tsx
  krampoline/src/components/memo/TextEditor.tsx
  krampoline/src/context/AuthContext.tsx
  krampoline/src/context/UserContext.tsx
  krampoline/src/hooks/useMemoActions.tsx
  krampoline/src/hooks/useMemoActionsInServer.tsx
  krampoline/src/hooks/useMemoStore.tsx
  krampoline/src/pages/Memo.tsx
  krampoline/src/pages/MyCalendar.tsx
  krampoline/src/service/database/api.ts
  krampoline/src/service/http-requests/memo-api.ts
  krampoline/src/service/http-requests/todo-api.ts
  krampoline/src/types/Auth.types.ts
  krampoline/src/utils/memo.ts
  krampoline/src/utils/token.ts
  krampoline/tailwind.config.js
Labels: new feature
